
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (1,'MESUT YILMAZ' ,'553 402 50 64' ,'ANKARA' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (2,'ALI'			 ,'2131'	,'ANKARA' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (3,'VELI'		 ,'32213'	,'BURDUR' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (4,'DURMUS'		 ,'75721321','MANISA' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (5,'HALIL'		 ,'323232'	,'VESTEL' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (6,'MUHARREM'	 ,'434343'	,'KONYA'  	);

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (7,'zuluf'		 ,'34343'	 ,'antep' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (8,'sema'		 ,'43434'	 ,'maras' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (9,'zeynep'		 ,'42434342' ,'bitlis'  );

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (10,'elizabeth'	 ,'434343'	 ,'mus' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (11,'fatma'		 ,'21412321' ,'manisa' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (12,'fatos'		 ,'2321321'	 ,'kocaeli' );

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (13,'vatos'		 ,'3454353'	,'bitlis' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (14,'rustem'		 ,'213213'	,'kirikkale');
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (15,'maho'		 ,'3243242'	,'konya'  	);

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (16,'saban'		 ,'21312321' ,'konya' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (17,'necip'		 ,'234234'	 ,'eruzum' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (18,'hakan'		 ,'2343242'	 ,'bitlis'  );

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (19,'esmeray'	 ,'123213'	 ,'antep' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (20,'saray'		 ,'324324'	 ,'maras' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (21,'hurrem'		 ,'123213'	 ,'mus'  	);

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (22,'elizabeth'	 ,'434343'	 ,'antep' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (23,'fatma'		 ,'21412321' ,'maras' 	);
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (24,'fatos'		 ,'2321321'	 ,'kocaeli' );

INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (25,'saban'		 ,'21312321' ,'kirikkale' );
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (26,'necip'		 ,'234234'	 ,'bitlis' 	  );
INSERT INTO T_USER (ID,NAME,PHONENUMBER,ADRESS) VALUES (27,'hakan'		 ,'2343242'	 ,'kocaeli'   );
