

CREATE TABLE IF NOT EXISTS PUBLIC.T_USER(
    ID 			BIGINT NOT NULL,
    NAME 		VARCHAR(255),
    PHONENUMBER VARCHAR(255),
	ADRESS		VARCHAR(255)
);            
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
CREATE SEQUENCE PUBLIC.USER_SEQUENCE START WITH 100;

